apiVersion: batch/v1
kind: Job
metadata:
  name: nvidia-smi
  namespace: <MY NAMESPACE>
spec:
  template:
    metadata:
      name: nvidia-smi
    spec:
      containers:
        - name: nvidia-smi
          image: 'nvcr.io/nvidia/cuda:12.1.0-runtime-ubuntu20.04'
          command:
            - nvidia-smi
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - <MY NODE NAME>
